# Generated by Django 3.1.3 on 2020-12-24 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0009_auto_20201222_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='Bloglikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
