# Generated by Django 3.1.3 on 2021-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20201225_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='2020/12/15/logo2.jpg', null=True, upload_to='%Y/%m/%d'),
        ),
    ]
